theme: jekyll-theme-minimal
title: Charlie Zhang
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - another-jekyll-plugin
  
  gem install jekyll-gist jekyll-coffeescript jekyll-assets another-jekyll-plugin
