theme: jekyll-theme-minimal
title: Charlie Zhang
logo: []
authors: ['Charlie Zhang']
email: ['cz317@georgetown.edu']
description: > # this means to ignore newlines until "baseurl:"
  MS DSPP 22' @Georgetown University

github:
  is_project_page: false

minimal:
  social_links:
    twitter_username: charliecxzhang
