theme: jekyll-theme-minimal
title: Charlie Zhang
author: Charlie Zhang
email: cz317@georgetown.edu
description: > # this means to ignore newlines until "baseurl:"
  DSPP student at Georgetown University

github:
  is_project_page: false

# Social Media Links 
twitter_username: charliecxzhang
